name: compile cookbok in latex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@latest

      - name: set up latex
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: compile latex document
        run: |
          pdflatex -interaction=nonstopmode main.tex
          pdflatex -interaction=nonstopmode main.tex 

      - name: upload pdf as artifact
        uses: actions/upload-artifact@latest
        with:
          name: monkey-cooks-pdf
          path: main.pdf
